const COLORS = {
  bgcLight: "#E3E6EC", //background color for light theme ...
  bgcDark: "#191A1D", //background color for dark theme ...
  gradientOrange: "#FF6161", //first color in gradient buttons ...
  gradientPink: "#FF61DC", // second color in gradient buttons ...
  blackText: "#393939", //will be used in black texts ...
  grayDark: "#616167", //will be used in RoomLarge card detail text ...
  grayLight: "#DFDEDE", //switch button background ...
  gray: "#999999", //will be used in gray texts ...
  white: "#FFFFFF",
  offWhite: "#F5F5F5",
  peach: "#FFB489",
  opaqueFirst: "#FFC7A7", //will be used in notifications gradient ...
  opaqueSecond: "#FFD579", //will be used in notifications gradient ...
  tabNavIcon: "#BDBDBD", //will be used in tab-navigation icons background (Home, Search ...)
  darkPriceInCards: "#434343", //dark price color in cards
  imgLoad: "#C4C4C4", //background for not loaded images
  homeScreenCatalogueBackground: "#FAFAFB",
  pink: "#FF61A8", // Pink text color
};

export default COLORS;
